name: style_kit
description: A new Flutter package project.
version: 0.0.1
# homepage: https://github.com/style_kit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: OpenSansBold
      fonts:
        - asset: lib/fonts/OpenSans-Bold.ttf
    - family: OpenSansBoldItalic
      fonts:
        - asset: lib/fonts/OpenSans-BoldItalic.ttf
    - family: OpenSansExtraBold
      fonts:
        - asset: lib/fonts/OpenSans-ExtraBold.ttf
    - family: OpenSansExtraBoldItalic
      fonts:
        - asset: lib/fonts/OpenSans-ExtraBoldItalic.ttf
    - family: OpenSansItalic
      fonts:
        - asset: lib/fonts/OpenSans-Italic.ttf
    - family: OpenSansLight
      fonts:
        - asset: lib/fonts/OpenSans-Light.ttf
    - family: OpenSansLightItalic
      fonts:
        - asset: lib/fonts/OpenSans-LightItalic.ttf
    - family: OpenSansRegular
      fonts:
        - asset: lib/fonts/OpenSans-Regular.ttf
    - family: OpenSansSemiBold
      fonts:
        - asset: lib/fonts/OpenSans-SemiBold.ttf
    - family: OpenSansSemiBoldItalic
      fonts:
        - asset: lib/fonts/OpenSans-SemiBoldItalic.ttf
